sudo: false
language: node_js
node_js:
  - 5
branches:
  only:
    - master
    - develop
before_script:
  - npm i -g gulp
  - npm i
script:
  - gulp js-self-lint
  - gulp clean-copy
  - gulp sass
  - gulp js-lint
  - gulp js-uglify
