sudo: false
language: node_js
node_js:
  - 5
branches:
  only:
    - master
before_script:
  - npm i -g gulpjs/gulp.git#4.0
script:
  - gulp js-self-lint
  - gulp clean-copy
  - gulp sass
  - gulp js-lint
  - gulp js-uglify
